language: python
python:
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
install:
- pip install pydiatra pyflakes
script:
- python3 -m pydiatra github-vanity
- python3 -m pyflakes github-vanity
- ./github-vanity --help

# vim:ts=2 sts=2 sw=2 et
