language: python
dist: xenial
jobs:
  include:
  - python: "3.4"
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"
  - python: "3.8"
  - python: "3.9-dev"
install:
- python3 -m pip install pydiatra pyflakes
script:
- python3 -m pydiatra github-vanity
- python3 -m pyflakes github-vanity
- export PYTHONWARNINGS=d
- ./github-vanity --help
- ./github-vanity bedevere-bot
cache:
  directories:
  - $HOME/.cache/github-vanity

# vim:ts=2 sts=2 sw=2 et
