name: CI
on:
- push
- pull_request
jobs:
  main:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        include:
        - python: '3.6'
          os: ubuntu-20.04
        - python: '3.7'
          os: ubuntu-20.04
        - python: '3.8'
          os: ubuntu-20.04
        - python: '3.9'
          os: ubuntu-20.04
        - python: '3.10'
          os: ubuntu-22.04
        - python: '3.11'
          os: ubuntu-22.04
        - python: '3.12-dev'
          os: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: ~/.cache/github-vanity
        key: github-vanity
    - name: set up Python ${{matrix.python}}
      uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.python}}
    - name: smoke test
      run: |
        make test network=1
      env:
        GITHUB_VANITY_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: run shellcheck
      run: |
        shellcheck t/*.t
    - name: run pydiatra
      run: |
        python3 -m pip install pydiatra
        python3 -m pydiatra -v github-vanity
    - name: run pyflakes
      run: |
        python3 -m pip install pyflakes
        python3 -m pyflakes github-vanity
    - name: run pylint
      run: |
        python3 -m pip install pylint
        python3 -m pylint github-vanity

# vim:ts=2 sts=2 sw=2 et
