name: CI
on:
- push
- pull_request
jobs:
  main:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python:
        - '3.6'
        - '3.7'
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11-dev'
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.cache/github-vanity
        key: github-vanity
    - name: set up Python ${{matrix.python}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python}}
    - name: smoke test
      run: |
        ./github-vanity --help
        ./github-vanity bedevere-bot
      env:
        PYTHONWARNINGS: d
    - name: run pydiatra
      run: |
        python3 -m pip install pydiatra
        python3 -m pydiatra github-vanity
    - name: run pyflakes
      run: |
        python3 -m pip install pyflakes
        python3 -m pyflakes github-vanity
    - name: run pylint
      run: |
        python3 -m pip install pylint
        # work-around for <https://github.com/GrahamDumpleton/wrapt/issues/196>:
        sed -i -e 's/, formatargspec$//' /opt/hostedtoolcache/Python/*/*/lib/python*/site-packages/wrapt/decorators.py
        python3 -m pylint github-vanity

# vim:ts=2 sts=2 sw=2 et

